const ExcelJS = require('exceljs')

const BRAND_ARGB = 'FF6366F1'
const WHITE_ARGB = 'FFFFFFFF'
const MUTED_ARGB = 'FF64748B'
const LIGHT_ARGB = 'FF94A3B8'
const ALT_ARGB   = 'FFF8FAFC'

const addTitleBlock = (ws, lastCol, branding, subtitle) => {
  ws.mergeCells(`A1:${lastCol}1`)
  const titleCell = ws.getCell('A1')
  titleCell.value = `InQuest Global — ${subtitle}`
  titleCell.font = { bold: true, size: 14, color: { argb: BRAND_ARGB } }
  titleCell.alignment = { vertical: 'middle' }
  ws.getRow(1).height = 26

  ws.mergeCells(`A2:${lastCol}2`)
  ws.getCell('A2').value =
    `Generated by: ${branding.generatedBy.name} (${branding.generatedBy.role})   ·   ${branding.generatedAt.toLocaleString('en-IN')}`
  ws.getCell('A2').font = { size: 9, color: { argb: LIGHT_ARGB } }
}

const addHeaderRow = (ws, headers) => {
  const row = ws.addRow(headers)
  row.height = 22
  row.eachCell((cell) => {
    cell.font      = { bold: true, color: { argb: WHITE_ARGB }, size: 9 }
    cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_ARGB } }
    cell.alignment = { vertical: 'middle', horizontal: 'left' }
    cell.border    = { bottom: { style: 'thin', color: { argb: 'FF4F46E5' } } }
  })
  return row
}

const shadeAlternate = (row, idx) => {
  if (idx % 2 !== 0) return
  row.eachCell((cell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ALT_ARGB } }
  })
}

const buildAnalyticsXlsx = async (data, branding) => {
  const { pipeline, trend, performers } = data
  const wb = new ExcelJS.Workbook()
  wb.creator = branding.generatedBy.name
  wb.created = branding.generatedAt

  // ── Sheet 1: Pipeline by Stage ────────────────────────────────────────────────
  const pipeSheet = wb.addWorksheet('Pipeline by Stage')
  pipeSheet.getColumn(1).width = 24
  pipeSheet.getColumn(2).width = 14
  addTitleBlock(pipeSheet, 'B', branding, 'Pipeline by Stage')
  pipeSheet.addRow([])
  addHeaderRow(pipeSheet, ['Stage', 'Leads'])
  pipeline.forEach((p, idx) => {
    const row = pipeSheet.addRow([p.status, p.count])
    shadeAlternate(row, idx)
  })

  // ── Sheet 2: Revenue Trend ───────────────────────────────────────────────────
  const trendSheet = wb.addWorksheet('Revenue Trend')
  trendSheet.getColumn(1).width = 14
  trendSheet.getColumn(2).width = 18
  trendSheet.getColumn(3).width = 14
  addTitleBlock(trendSheet, 'C', branding, 'Revenue Trend (Last 6 Months)')
  trendSheet.addRow([])
  addHeaderRow(trendSheet, ['Month', 'Revenue (₹)', 'Deals Won'])
  trend.forEach((t, idx) => {
    const row = trendSheet.addRow([t.month, t.revenue, t.count])
    row.getCell(2).numFmt = '"₹"#,##0.00'
    shadeAlternate(row, idx)
  })

  // ── Sheet 3: Top Performers ──────────────────────────────────────────────────
  const perfSheet = wb.addWorksheet('Top Performers')
  perfSheet.getColumn(1).width = 24
  perfSheet.getColumn(2).width = 14
  perfSheet.getColumn(3).width = 24
  perfSheet.getColumn(4).width = 12
  perfSheet.getColumn(5).width = 16
  addTitleBlock(perfSheet, 'E', branding, 'Top Performers')
  perfSheet.addRow([])
  addHeaderRow(perfSheet, ['Rep', 'Role', 'Total Leads', 'Won', 'Revenue (₹)'])
  performers.forEach((p, idx) => {
    const row = perfSheet.addRow([p.user.name, p.user.role, p.totalLeads, p.won, p.revenue])
    row.getCell(5).numFmt = '"₹"#,##0.00'
    shadeAlternate(row, idx)
  })

  return wb
}

module.exports = { buildAnalyticsXlsx }
