const fs   = require('fs')
const path = require('path')

// ── Color palette (no purple) ─────────────────────────────────────────────────
const BANNER_BG  = '#0F172A' // dark navy — matches app sidebar
const BANNER_SUB = '#94A3B8' // muted slate for subtitle text
const DARK       = '#0F172A'
const MUTED      = '#64748B'
const LIGHT      = '#94A3B8'
const BORDER     = '#E2E8F0'
const SECTION_FG = '#1E293B' // section header text
const TABLE_HDR  = '#F1F5F9' // table header background

// Keep BRAND alias so leadPdf / projectPdf that import it still work
const BRAND = SECTION_FG

// ── Layout ────────────────────────────────────────────────────────────────────
const MARGIN    = 50
const PAGE_W    = 595 // A4 portrait
const CONTENT_W = PAGE_W - MARGIN * 2
const BANNER_H  = 76

// ── Logo: extract embedded PNG from the SVG once, cache it ───────────────────
const LOGO_PATH = path.resolve(__dirname, '../../frontend/public/company.svg')
let _logoBuffer = undefined // undefined = not yet loaded; null = failed

const getLogoBuffer = () => {
  if (_logoBuffer !== undefined) return _logoBuffer
  try {
    const svg   = fs.readFileSync(LOGO_PATH, 'utf8')
    const match = svg.match(/data:image\/png;base64,([A-Za-z0-9+/=]+)/)
    _logoBuffer = match ? Buffer.from(match[1], 'base64') : null
  } catch {
    console.warn('[pdfHelpers] could not load logo from', LOGO_PATH)
    _logoBuffer = null
  }
  return _logoBuffer
}

// ── Helpers ───────────────────────────────────────────────────────────────────
const fmtDate = (d) =>
  d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'

const fmtDateTime = (d) =>
  d ? new Date(d).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—'

const fmtCurrency = (v) =>
  `₹${(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

// ── Banner ────────────────────────────────────────────────────────────────────
// Logo natural size: 453 × 150 px (aspect ≈ 3.02 : 1)
const LOGO_H      = 46
const LOGO_W      = Math.round(LOGO_H * (453 / 150)) // ≈ 139
const LOGO_Y      = (BANNER_H - LOGO_H) / 2          // vertically centred

const drawBanner = (doc, branding) => {
  // Background
  doc.rect(0, 0, PAGE_W, BANNER_H).fill(BANNER_BG)

  const logo = getLogoBuffer()
  if (logo) {
    doc.image(logo, MARGIN, LOGO_Y, { width: LOGO_W, height: LOGO_H })
  }

  // Document subtitle — to the right of the logo (or left-aligned if no logo)
  const titleX = logo ? MARGIN + LOGO_W + 16 : MARGIN
  const titleW = PAGE_W - titleX - MARGIN

  doc.fillColor(BANNER_SUB).fontSize(10).font('Helvetica')
    .text(branding.documentTitle, titleX, (BANNER_H - 10) / 2, {
      width:     titleW,
      lineBreak: false,
    })

  // Explicitly move cursor below the banner so subsequent content doesn't
  // overlap — pdfkit updates doc.y to wherever text was last rendered,
  // which may be inside the banner area when text is positioned absolutely.
  doc.y = BANNER_H + 14
  doc.fillColor(DARK)
}

// ── Meta bar ──────────────────────────────────────────────────────────────────
const drawMeta = (doc, branding) => {
  const from = fmtDate(branding.dateRange.from)
  const to   = fmtDate(branding.dateRange.to)

  doc.fontSize(8).font('Helvetica').fillColor(LIGHT)
    .text(
      `Generated by: ${branding.generatedBy.name} (${branding.generatedBy.role})` +
      `   ·   ${fmtDateTime(branding.generatedAt)}` +
      `   ·   Period: ${from} – ${to}`,
      MARGIN, doc.y,
      { width: CONTENT_W }
    )
  doc.moveDown(0.5)
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y)
    .strokeColor(BORDER).lineWidth(0.5).stroke()
  doc.moveDown(0.7)
  doc.fillColor(DARK)
}

// ── Section header ────────────────────────────────────────────────────────────
const drawSectionHeader = (doc, text) => {
  doc.moveDown(0.5)
  if (doc.y > doc.page.height - 130) { doc.addPage() }

  doc.fontSize(9).font('Helvetica-Bold').fillColor(SECTION_FG)
    .text(text.toUpperCase(), MARGIN, doc.y)
  doc.moveDown(0.2)
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y)
    .strokeColor('#CBD5E1').lineWidth(0.8).stroke()
  doc.moveDown(0.45)
  doc.font('Helvetica').fillColor(DARK)
}

// ── Key-value field ───────────────────────────────────────────────────────────
const drawField = (doc, label, value) => {
  const LABEL_W = 140
  const startY  = doc.y

  doc.fontSize(9).font('Helvetica-Bold').fillColor(MUTED)
    .text(label, MARGIN, startY, { width: LABEL_W, lineBreak: false })
  const afterLabel = doc.y

  doc.font('Helvetica').fillColor(DARK)
    .text(String(value || '—'), MARGIN + LABEL_W, startY, { width: CONTENT_W - LABEL_W })

  doc.y = Math.max(afterLabel, doc.y) + 3
}

// ── Divider ───────────────────────────────────────────────────────────────────
const drawDivider = (doc) => {
  doc.moveDown(0.4)
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y)
    .strokeColor(BORDER).lineWidth(0.4).stroke()
  doc.moveDown(0.4)
}

// ── Page numbers (call after all content, before doc.end()) ──────────────────
const addPageNumbers = (doc) => {
  const range = doc.bufferedPageRange()
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i)
    doc.fontSize(7.5).font('Helvetica').fillColor(LIGHT)
      .text(
        `InQuest Global · Confidential · Page ${i + 1} of ${range.count}`,
        MARGIN, doc.page.height - 28,
        { width: CONTENT_W, align: 'center' }
      )
  }
}

module.exports = {
  BRAND, DARK, MUTED, LIGHT, BORDER, MARGIN, PAGE_W, CONTENT_W, BANNER_H,
  TABLE_HDR, SECTION_FG,
  fmtDate, fmtDateTime, fmtCurrency,
  drawBanner, drawMeta, drawSectionHeader, drawField, drawDivider, addPageNumbers,
}
