const ExcelJS = require('exceljs')

const BRAND_ARGB  = 'FF6366F1'
const WHITE_ARGB  = 'FFFFFFFF'
const MUTED_ARGB  = 'FF64748B'
const LIGHT_ARGB  = 'FF94A3B8'
const ALT_ARGB    = 'FFF8FAFC'

const COL_WIDTHS = [28, 20, 14, 48, 16, 18, 20, 15, 20, 15, 15, 15, 26]

const HEADERS = [
  'ID', 'Submitted By', 'Submitted On',
  'Items (Description · Amount)',
  'Total (₹)', 'Status',
  'Head Approver', 'Head Approved On',
  'Finance Approver', 'Finance Approved On',
  'Paid By', 'Paid On', 'Project',
]

const DATE_COLS = [3, 8, 10, 12] // 1-based

const buildReimbursementsXlsx = async (reimbursements, branding) => {
  const wb = new ExcelJS.Workbook()
  wb.creator = branding.generatedBy.name
  wb.created = branding.generatedAt

  const ws = wb.addWorksheet('Reimbursements')

  // Freeze through the header row (row 5)
  ws.views = [{ state: 'frozen', ySplit: 5, xSplit: 0, topLeftCell: 'A6', activeCell: 'A6' }]

  COL_WIDTHS.forEach((w, i) => { ws.getColumn(i + 1).width = w })

  // ── Row 1: title ────────────────────────────────────────────────────────────
  ws.mergeCells('A1:M1')
  const titleCell = ws.getCell('A1')
  titleCell.value = 'InQuest Global — Reimbursements Report'
  titleCell.font = { bold: true, size: 14, color: { argb: BRAND_ARGB } }
  titleCell.alignment = { vertical: 'middle' }
  ws.getRow(1).height = 26

  // ── Row 2: date range ────────────────────────────────────────────────────────
  ws.mergeCells('A2:M2')
  const from = branding.dateRange.from.toLocaleDateString('en-IN', { month: 'short', year: 'numeric' })
  const to   = branding.dateRange.to.toLocaleDateString('en-IN', { month: 'short', year: 'numeric' })
  ws.getCell('A2').value = `Period: ${from} – ${to}`
  ws.getCell('A2').font = { size: 10, color: { argb: MUTED_ARGB } }

  // ── Row 3: generated by ──────────────────────────────────────────────────────
  ws.mergeCells('A3:M3')
  ws.getCell('A3').value =
    `Generated by: ${branding.generatedBy.name} (${branding.generatedBy.role})   ·   ` +
    `${branding.generatedAt.toLocaleString('en-IN')}`
  ws.getCell('A3').font = { size: 9, color: { argb: LIGHT_ARGB } }

  // ── Row 4: spacer ────────────────────────────────────────────────────────────
  ws.getRow(4).height = 6

  // ── Row 5: column headers ────────────────────────────────────────────────────
  const headerRow = ws.addRow(HEADERS)
  headerRow.height = 22
  headerRow.eachCell((cell) => {
    cell.font      = { bold: true, color: { argb: WHITE_ARGB }, size: 9 }
    cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_ARGB } }
    cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: false }
    cell.border    = { bottom: { style: 'thin', color: { argb: 'FF4F46E5' } } }
  })

  // ── Data rows ────────────────────────────────────────────────────────────────
  reimbursements.forEach((r, idx) => {
    const itemsSummary = r.items
      .map((i) => `${i.description}  ₹${i.amount.toLocaleString('en-IN')}`)
      .join('  |  ')

    const rowValues = [
      r._id.toString(),
      r.submittedBy?.name  || '—',
      r.createdAt          ? new Date(r.createdAt)         : null,
      itemsSummary,
      r.totalAmount,
      r.status,
      r.headReviewedBy?.name    || '—',
      r.headReviewedAt          ? new Date(r.headReviewedAt)    : null,
      r.financeReviewedBy?.name || '—',
      r.financeReviewedAt       ? new Date(r.financeReviewedAt) : null,
      r.paidBy?.name     || '—',
      r.paidAt           ? new Date(r.paidAt) : null,
      r.project?.title   || '—',
    ]

    const row = ws.addRow(rowValues)

    // Alternate row shading
    if (idx % 2 === 0) {
      row.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ALT_ARGB } }
      })
    }

    // Currency format
    row.getCell(5).numFmt = '"₹"#,##0.00'

    // Date formats
    DATE_COLS.forEach((col) => {
      const cell = row.getCell(col)
      if (cell.value instanceof Date) cell.numFmt = 'dd-mmm-yyyy'
    })

    // Wrap items column
    row.getCell(4).alignment = { wrapText: true, vertical: 'top' }
    row.height = Math.max(16, Math.min(r.items.length * 15, 72))
  })

  // ── Totals section ────────────────────────────────────────────────────────────
  ws.addRow([])

  const sumTitleRow = ws.addRow(['SUMMARY'])
  sumTitleRow.getCell(1).font = { bold: true, size: 10, color: { argb: BRAND_ARGB } }

  const groups = [
    { label: 'Pending',          filter: (r) => r.status === 'Pending' },
    { label: 'Approved (all)',   filter: (r) => ['Head Approved', 'Finance Approved'].includes(r.status) },
    { label: 'Paid',             filter: (r) => r.status === 'Paid' },
    { label: 'Rejected',         filter: (r) => r.status === 'Rejected' },
  ]

  groups.forEach(({ label, filter }) => {
    const subset = reimbursements.filter(filter)
    const total  = subset.reduce((s, r) => s + r.totalAmount, 0)
    const row    = ws.addRow(['', `${label} (${subset.length})`, '', '', total])
    row.getCell(2).font = { size: 9 }
    row.getCell(5).numFmt = '"₹"#,##0.00'
  })

  ws.addRow([])
  const paidRecords  = reimbursements.filter((r) => r.status === 'Paid')
  const paidTotal    = paidRecords.reduce((s, r) => s + r.totalAmount, 0)
  const grandRow     = ws.addRow(['', `Paid in Account (${paidRecords.length} records)`, '', '', paidTotal])
  grandRow.getCell(2).font = { bold: true, size: 11 }
  grandRow.getCell(5).numFmt = '"₹"#,##0.00'
  grandRow.getCell(5).font  = { bold: true, size: 11, color: { argb: BRAND_ARGB } }

  return wb
}

module.exports = { buildReimbursementsXlsx }
